// Hero background: "KOROTENKY" drawn by Fourier epicycles, then sharpened by
// adding terms until the partial sums converge on the glyphs.
//
// GENERATED by animation/build-fourier-bg.mjs from fourier-bg.template.js.
//
// Markup: <div data-fourier aria-hidden="true"></div> (must have a size).
// Colours come from the CSS variables --color-text, --color-accent and
// --color-text-subtle, so it follows the site's light/dark theme.
(() => {
  const container = document.querySelector("[data-fourier]");
  if (!container || !window.requestAnimationFrame) {
    return;
  }

  // Fourier coefficients of each glyph outline of the word, precomputed by
  // the build script (KaTeX_Main-Regular glyphs, word spans x in [-0.5, 0.5],
  // y down). Per contour: flat [freq, re, im, ...] with re/im scaled by
  // COEF_SCALE; the DC term first, then by decreasing amplitude.
  const WORD_HEIGHT = 0.0989;
  const COEF_SCALE = 100000;
  const TERMS = [
    [0,-45529,6,1,-3384,1393,-3,628,1386,3,-483,973,5,-81,-610,-7,-461,280,4,-83,468,-4,-36,-358,-9,231,58,-1,198,16,7,-160,-102,11,117,-132,2,-169,-26,-11,72,128,-6,-81,71,13,-11,91,9,66,-64,-10,84,-29,-5,69,52,-14,-41,54,23,32,55,-19,47,41,12,21,-51,10,26,48,-2,48,-26,-15,35,-30,20,27,-35,24,27,34,19,28,-32,18,35,-9,-8,-11,35,6,-23,26,17,10,33,-17,-22,-24,-13,3,-31,25,-30,-3,15,24,15,-16,1,27,-12,25,10,-18,26,6,8,24,11,21,17,19,30,-3,24,22,-20,12,16,-2,-23,26,10,-18,29,-9,-19,-20,17,11,32,7,20,-23,20,4,36,-19,5,28,12,12,14,-12,-11,-36,16,5,-21,1,-16,-26,15,6,-22,-16,0,-35,12,-8,-28,13,-5,35,-12,5,-24,-12,-1,41,11,-1,-48,-4,-10,-33,-8,6,-45,7,7,38,10,1,33,4,9,-29,0,9,31,6,7,-34,7,5,40,-8,-2,-65,3,7,48,3,-6,42,-7,-1,-27,4,6,-25,-2,-7,37,-3,-6,52,7,-1,34,0,-7,-60,-2,6,-31,4,-4,49,-2,-5,-39,5,1,-77,5,-3,27,0,5,-32,-5,2,44,-3,-4,-51,3,-5,53,4,3,45,-3,4,-43,3,-4,60,2,4,-72,4,0,50,0,4,61,4,-1,-69,4,-1,-42,4,2,-63,-4,-1,-54,4,-1,-37,-4,0,-46,3,-2,-44,4,-1,-61,-2,-3,-53,-2,3,43,0,4,-64,2,3,-50,-1,3,-75,0,4,65,0,3,39,-2,2,-78,2,-3,58,2,-3,-56,-2,3,-81,-1,-3,-82,0,3,70,2,1,-38,-3,1,-55,-2,-2,-57,3,0,-86,3,-1,55,-2,-1,51,-1,-3,-67,-2,2,-90,-2,-2,-73,-1,2,-74,1,2,-79,2,0,66,-2,1,-41,-2,-1],
    [0,-33387,7,1,4737,-2,-1,-154,-1,3,-51,0,-2,1,4,4,1,-2,-7,-2,0,5,1,0,-6,0,1,-5,-1,1,9,-1,0,-4,1,0,8,0,-1,7,-1,-1,-3,1,0,6,1,0,-10,0,-1,-8,0,0,-13,0,0,10,0,0,-9,0,0,12,0,0,11,0,0,15,0,0,2,0,0,-12,0,0,14,0,0,-15,0,0,-18,0,0,20,0,0,-21,0,0,-16,0,0,13,0,0,-11,0,0,-23,0,0,17,0,0,23,0,0,18,0,0,25,0,0,-31,0,0,-28,0,0,30,0,0,33,0,0,-19,0,0,21,0,0,-17,0,0,-29,0,0,31,0,0,19,0,0,-36,0,0,-14,0,0,-41,0,0,43,0,0,38,0,0,-37,0,0,35,0,0,39,0,0,-40,0,0,-33,0,0,-32,0,0,42,0,0,-26,0,0,34,0,0,28,0,0,-22,0,0,16,0,0,-20,0,0,24,0,0,-24,0,0,22,0,0,26,0,0,-35,0,0,-42,0,0,44,0,0,-49,0,0,-25,0,0,37,0,0,-48,0,0,-39,0,0,51,0,0,36,0,0,48,0,0,50,0,0,-46,0,0,-30,0,0,40,0,0,-62,0,0,-34,0,0,27,0,0,64,0,0,41,0,0,-70,0,0,-38,0,0,-43,0,0,72,0,0,-63,0,0,65,0,0,54,0,0,45,0,0,32,0,0,-52,0,0,-71,0,0,-45,0,0,73,0,0,49,0,0,-47,0,0,47,0,0,69,0,0,-67,0,0,70,0,0,-44,0,0,-68,0,0,-76,0,0,78,0,0,-75,0,0,77,0,0,75,0,0,66,0,0,-73,0,0,-56,0,0,-64,0,0,58,0,0,-97,0,0,-74,0,0,-58,0,0,46,0,0,99,0,0,60,0,0,76,0,0],
    [0,-33389,-29,-1,1061,-3505,1,-156,-524,-3,141,-117,3,12,10,2,9,12,-4,-7,2,-5,6,-1,-2,2,-3,5,-4,1,-7,2,1,-6,-1,0,11,0,-1,-9,0,1,7,0,1,-11,0,0,-13,0,-1,9,0,0,10,0,0,6,0,0,12,0,0,-16,0,0,13,0,0,14,0,0,15,0,0,-17,0,0,-8,0,0,-15,0,0,4,0,0,-14,0,0,-12,0,0,22,0,0,18,0,0,8,0,0,-20,0,0,25,0,0,-24,0,0,17,0,0,-19,0,0,-26,0,0,-27,0,0,24,0,0,20,0,0,-22,0,0,-21,0,0,-10,0,0,21,0,0,31,0,0,-33,0,0,19,0,0,-23,0,0,-30,0,0,-29,0,0,28,0,0,29,0,0,16,0,0,35,0,0,-18,0,0,-37,0,0,27,0,0,38,0,0,-40,0,0,-28,0,0,26,0,0,-31,0,0,34,0,0,36,0,0,32,0,0,-36,0,0,23,0,0,-38,0,0,42,0,0,45,0,0,33,0,0,-35,0,0,-46,0,0,-34,0,0,-44,0,0,47,0,0,-39,0,0,-49,0,0,-42,0,0,-47,0,0,-51,0,0,37,0,0,41,0,0,-43,0,0,44,0,0,40,0,0,-58,0,0,56,0,0,50,0,0,49,0,0,43,0,0,-41,0,0,-52,0,0,39,0,0,54,0,0,59,0,0,-61,0,0,51,0,0,-32,0,0,-45,0,0,-53,0,0,63,0,0,-25,0,0,46,0,0,-54,0,0,-56,0,0,-65,0,0,52,0,0,-48,0,0,30,0,0,-55,0,0,53,0,0,60,0,0,-62,0,0,-60,0,0,-71,0,0,57,0,0,70,0,0,-50,0,0,-57,0,0,-74,0,0,-67,0,0,66,0,0,48,0,0,76,0,0,55,0,0],
    [0,-22243,841,1,-3684,231,2,94,1482,-2,310,1176,-3,636,-50,4,-275,-539,-5,-405,-20,3,-166,310,-1,-15,-328,-4,-225,230,-6,-78,301,9,37,-188,-7,186,10,7,54,-168,8,97,140,-9,86,59,-8,95,31,5,-36,92,14,52,-60,6,-39,-62,-12,-69,-13,10,39,43,-15,53,25,17,3,54,12,-8,51,-13,50,6,-10,-23,44,-11,45,-8,16,31,-29,19,18,35,15,29,-4,24,5,28,18,8,19,25,13,13,-18,-4,-17,-19,-12,12,-21,11,12,-22,12,-11,-20,15,-4,-14,-4,14,26,-7,12,22,-14,1,13,2,14,21,-2,-14,29,-13,4,-28,12,6,-23,-2,12,20,6,11,-16,9,5,-34,10,-1,27,-9,-4,23,9,-3,32,8,-4,-31,-8,-4,-29,7,0,28,-7,0,41,6,0,37,5,-3,38,-5,-4,-17,6,1,-25,1,6,33,-5,2,-30,5,1,-35,5,1,36,-4,-4,42,5,2,-27,5,1,31,-5,-1,-39,2,-5,-51,3,4,46,4,2,51,0,4,-60,3,-3,-61,4,-2,-38,-2,-4,30,4,0,-52,1,4,45,-3,-2,-50,0,3,39,3,-1,48,3,1,-62,2,-2,35,-2,2,-24,-3,0,-26,0,-3,-33,2,2,34,-3,1,-57,0,3,-55,2,-2,-59,1,2,54,0,-3,11,2,2,-68,2,1,-58,0,2,-56,2,1,-45,-2,1,-48,-1,-2,-40,-2,1,52,-2,0,-67,1,-2,-47,-2,1,-53,1,-2,-71,-2,-1,-37,2,-1,60,0,2,55,2,1,-44,2,-1,-42,0,2,53,1,2,-43,-1,-1,68,1,0,40,-1,-1,-69,0,-2,-81,-1,1,47,1,0,-49,-1,1,-36,0,-1,-84,1,0,85,1,-1,61,0,-1,94,1,1,-65,0,-1,69,0,1,58,0,1,-64,-1,1,90,1,-1,117,1,0,59,1,-1,-70,-1,-1],
    [0,-22289,-2117,-1,1906,-528,3,-83,-90,2,99,67,-2,57,-24,1,-43,-30,-5,-9,49,-4,17,-34,6,1,-24,-3,-12,10,-8,9,13,5,-2,14,7,-3,11,4,7,8,-7,-4,-9,9,8,-4,-11,8,0,10,-7,4,-9,-6,-4,-12,-6,1,-6,-1,5,13,-4,-2,-15,-2,4,14,3,1,-14,2,-2,11,3,-1,-18,1,2,12,2,1,17,0,2,-19,-1,-2,-16,1,-2,16,0,-2,-10,-1,-2,-22,-2,0,20,-1,1,21,1,-1,-13,1,-1,-21,1,0,-26,1,-1,-23,1,0,-25,-1,1,18,0,-1,24,1,0,19,1,0,-29,0,-1,8,0,-1,23,-1,0,27,0,1,15,-1,0,-33,1,0,25,-1,0,28,0,-1,-17,0,-1,-30,0,1,-32,-1,0,31,0,0,22,0,1,-20,1,0,-36,0,0,-28,0,1,26,0,0,29,0,0,32,0,0,30,0,0,34,0,0,-40,0,0,35,0,0,-37,0,0,-39,0,0,39,0,0,-27,0,0,36,0,0,-43,0,0,38,0,0,33,0,0,42,0,0,-24,0,0,-44,0,0,-35,0,0,37,0,0,-47,0,0,46,0,0,43,0,0,-34,0,0,41,0,0,-41,0,0,-51,0,0,49,0,0,-46,0,0,45,0,0,40,0,0,-50,0,0,-48,0,0,-54,0,0,44,0,0,50,0,0,53,0,0,-58,0,0,47,0,0,-55,0,0,-31,0,0,56,0,0,52,0,0,-42,0,0,-61,0,0,48,0,0,54,0,0,57,0,0,-38,0,0,51,0,0,-57,0,0,-53,0,0,60,0,0,-65,0,0,-45,0,0,-62,0,0,59,0,0,61,0,0,64,0,0,-49,0,0,-52,0,0,63,0,0,-68,0,0,55,0,0,-69,0,0,-59,0,0,58,0,0,67,0,0,-72,0,0],
    [0,-10624,7,1,4737,-2,-1,-154,-1,3,-51,0,-2,1,4,4,1,-2,-7,-2,0,5,1,0,-6,0,1,-5,-1,1,9,-1,0,-4,1,0,8,0,-1,7,-1,-1,-3,1,0,6,1,0,-10,0,-1,-8,0,0,-13,0,0,10,0,0,-9,0,0,12,0,0,11,0,0,15,0,0,2,0,0,-12,0,0,14,0,0,-15,0,0,-18,0,0,20,0,0,-21,0,0,-16,0,0,13,0,0,-11,0,0,-23,0,0,17,0,0,23,0,0,18,0,0,25,0,0,-31,0,0,-28,0,0,30,0,0,33,0,0,-19,0,0,21,0,0,-17,0,0,-29,0,0,31,0,0,19,0,0,-36,0,0,-14,0,0,-41,0,0,43,0,0,38,0,0,-37,0,0,35,0,0,39,0,0,-40,0,0,-33,0,0,-32,0,0,42,0,0,-26,0,0,34,0,0,28,0,0,-22,0,0,16,0,0,-20,0,0,24,0,0,-24,0,0,22,0,0,26,0,0,-35,0,0,-42,0,0,44,0,0,-49,0,0,-25,0,0,37,0,0,-48,0,0,-39,0,0,51,0,0,36,0,0,48,0,0,50,0,0,-46,0,0,-30,0,0,40,0,0,-62,0,0,-34,0,0,27,0,0,64,0,0,41,0,0,-70,0,0,-38,0,0,-43,0,0,72,0,0,-63,0,0,65,0,0,54,0,0,45,0,0,32,0,0,-52,0,0,-71,0,0,-45,0,0,73,0,0,49,0,0,-47,0,0,47,0,0,69,0,0,-67,0,0,70,0,0,-44,0,0,-68,0,0,-76,0,0,78,0,0,-75,0,0,77,0,0,75,0,0,66,0,0,-73,0,0,-56,0,0,-64,0,0,58,0,0,-97,0,0,-74,0,0,-58,0,0,46,0,0,99,0,0,60,0,0,76,0,0],
    [0,-10626,-29,-1,1061,-3505,1,-156,-524,-3,141,-117,3,12,10,2,9,12,-4,-7,2,-5,6,-1,-2,2,-3,5,-4,1,-7,2,1,-6,-1,0,11,0,-1,-9,0,1,7,0,1,-11,0,0,-13,0,-1,9,0,0,10,0,0,6,0,0,12,0,0,-16,0,0,13,0,0,14,0,0,15,0,0,-17,0,0,-8,0,0,-15,0,0,4,0,0,-14,0,0,-12,0,0,22,0,0,18,0,0,8,0,0,-20,0,0,25,0,0,-24,0,0,17,0,0,-19,0,0,-26,0,0,-27,0,0,24,0,0,20,0,0,-22,0,0,-21,0,0,-10,0,0,21,0,0,31,0,0,-33,0,0,19,0,0,-23,0,0,-30,0,0,-29,0,0,28,0,0,29,0,0,16,0,0,35,0,0,-18,0,0,-37,0,0,27,0,0,38,0,0,-40,0,0,-28,0,0,26,0,0,-31,0,0,34,0,0,36,0,0,32,0,0,-36,0,0,23,0,0,-38,0,0,42,0,0,45,0,0,33,0,0,-35,0,0,-46,0,0,-34,0,0,-44,0,0,47,0,0,-39,0,0,-49,0,0,-42,0,0,-47,0,0,-51,0,0,37,0,0,41,0,0,-43,0,0,44,0,0,40,0,0,-58,0,0,56,0,0,50,0,0,49,0,0,43,0,0,-41,0,0,-52,0,0,39,0,0,54,0,0,59,0,0,-61,0,0,51,0,0,-32,0,0,-45,0,0,-53,0,0,63,0,0,-25,0,0,46,0,0,-54,0,0,-56,0,0,-65,0,0,52,0,0,-48,0,0,30,0,0,-55,0,0,53,0,0,60,0,0,-62,0,0,-60,0,0,-71,0,0,57,0,0,70,0,0,-50,0,0,-57,0,0,-74,0,0,-67,0,0,66,0,0,48,0,0,76,0,0,55,0,0],
    [0,664,-858,1,-2717,-2156,-2,-1504,-350,3,-454,957,-1,644,-514,-4,-321,655,-3,-186,-390,-7,-5,361,6,-266,217,4,129,262,-5,159,-34,8,119,91,-9,122,30,13,-76,63,5,81,17,-6,59,50,12,72,15,-11,-29,56,16,-52,13,10,-21,44,-8,35,-27,2,-43,12,7,1,44,20,-30,26,-13,-27,-22,11,12,24,-12,23,-5,-10,9,21,23,-22,6,14,-1,-22,-15,-16,12,17,-8,18,22,16,11,18,-8,-16,-14,-1,17,-17,-7,-14,33,-16,-2,-21,1,-15,24,-5,12,-24,5,12,-22,-9,7,-16,11,3,-18,5,-10,-27,8,7,30,-10,3,37,-10,3,15,7,6,-19,9,-1,-30,-8,-2,34,-5,5,19,7,2,-48,-5,-5,-41,-5,-5,39,4,6,-25,-3,6,-31,-3,-6,21,0,7,-42,-1,7,32,3,6,26,-5,-1,25,3,5,-46,-2,4,-36,4,-3,-43,-4,3,40,-4,-1,-28,0,-4,-23,4,1,-61,-4,1,28,0,-4,-38,-2,-4,-33,-4,1,27,-3,3,-26,-4,1,-58,-4,-1,47,-4,0,44,-3,1,-34,-2,-2,-73,1,3,29,2,2,52,-1,3,-65,-3,-1,45,1,-3,51,-3,1,50,-2,-1,-53,-1,2,-63,0,3,-39,-1,2,36,-2,-1,-45,-1,-2,-70,0,2,-51,-2,-1,-47,2,0,-37,2,1,46,-1,-2,-56,0,2,38,1,-2,35,0,2,54,-2,0,-68,-2,0,-29,-2,1,-78,-2,1,-67,1,-2,-40,2,0,-60,-1,2,31,1,-2,42,0,2,43,-1,-1,64,-1,-1,-66,0,1,58,1,0,-83,1,1,-90,1,1,-75,-1,0,101,0,1,-79,-1,-1,84,0,1,98,0,1,88,1,1,115,0,1,91,0,1,-72,-1,0,-59,0,1,-89,-1,0,82,-1,0,-44,-1,0,-92,-1,0,9,-1,0,-62,-1,-1,118,-1,1],
    [0,11406,23,1,-2549,991,2,-1392,1181,-1,1336,378,-4,407,1077,3,-637,893,-2,-534,-377,4,170,-544,-7,-245,393,5,-69,-309,-8,207,-219,7,133,243,-5,-108,-205,-6,-129,175,11,178,-64,8,-104,-120,-12,104,71,-10,120,-36,-3,-93,58,6,-2,-108,-11,-102,24,-13,5,83,-9,23,80,10,-57,-46,16,15,60,12,20,-52,9,-13,46,22,-43,22,13,-37,20,-18,23,-31,23,21,30,26,10,34,21,34,8,20,21,-27,17,34,-3,25,31,-7,-15,5,-30,-14,-1,29,15,16,-24,-19,1,28,-20,27,6,19,25,-11,14,12,-24,27,23,-8,18,23,2,-17,11,20,-21,14,16,38,-14,8,29,-15,5,31,8,13,-25,-10,-10,-16,9,-11,32,-9,11,-26,6,12,-28,13,0,-29,6,12,-39,2,11,28,-10,3,-24,10,-2,33,3,10,42,-4,9,24,-9,2,-22,-9,4,-43,7,-6,40,6,7,36,-6,6,-37,8,3,34,7,-4,-31,-6,5,39,2,-7,-33,-1,7,-30,5,-5,43,-5,-6,-35,5,-5,-36,7,0,30,-2,6,44,0,-6,56,6,2,-27,4,-4,57,-5,-1,41,-1,-6,-50,3,-4,-40,4,-3,54,5,0,47,4,-3,-56,4,-2,45,-5,1,37,-4,-2,46,3,3,-38,-3,-3,-74,2,4,-41,-1,4,48,-4,-1,-57,-4,-1,-45,4,0,-68,1,4,60,4,0,-61,-2,3,-85,0,-4,49,1,-3,-48,1,3,-72,3,0,52,-3,1,-42,-1,-3,-23,3,-2,61,0,3,-75,3,-1,-53,1,3,-71,-2,-2,-52,0,-3,-70,3,0,-89,3,-2,-67,-1,3,62,1,3,63,2,-2,66,2,2,50,3,0,53,2,-1,75,1,3,-80,3,0,-79,2,-2,-103,2,2,69,1,2,-83,1,2,-62,-1,-2,-87,0,-2,-65,2,-1,74,0,-2,-64,0,2],
    [0,21891,-374,1,-2288,1744,3,1638,1008,-3,-887,1463,-1,-1225,166,2,308,214,-5,290,-162,-7,314,-83,-2,3,321,4,-317,47,5,-132,281,-11,176,61,-4,161,-36,11,148,-8,10,64,130,9,116,-79,-6,-54,-115,7,112,44,-13,51,100,6,87,-21,-9,65,-44,-12,73,-21,8,-27,-61,13,46,-45,16,53,-32,12,-39,-29,-14,-16,-41,25,37,23,-8,-42,9,15,16,-39,-15,35,-10,21,26,26,-19,-3,-34,22,-27,-19,18,-17,26,23,23,19,24,5,28,28,-14,25,14,-6,26,17,9,-25,-21,19,-19,-18,-6,23,27,18,-10,-22,-7,-20,-17,-3,19,-29,-17,-7,29,16,-4,-24,-16,1,20,-2,15,19,-5,14,30,13,-5,-39,-8,10,31,11,-6,-20,8,-9,39,6,9,-23,8,-7,-25,10,-4,-28,6,8,36,-9,-3,41,6,7,33,-4,7,26,6,6,42,-5,6,-30,-6,-5,38,-4,6,-16,-7,2,34,6,4,-10,-7,-2,-42,5,4,45,6,-2,-38,5,4,56,-5,4,35,-5,4,-45,-4,-4,47,6,-1,46,-2,6,-32,-3,5,-35,3,-5,32,-6,0,-31,-5,-2,-44,-3,4,48,3,4,44,3,3,-72,5,-1,-34,-3,3,-62,0,4,55,1,4,-36,4,-2,62,2,4,-74,4,3,-41,0,4,-78,2,3,-64,2,4,-37,-3,2,-47,-1,4,-26,3,2,-54,2,3,-56,4,0,52,3,1,37,3,1,-60,-1,3,40,-3,1,-75,-2,3,-43,-3,1,58,-3,-1,-27,3,-1,50,-3,-2,-50,1,-3,60,-1,3,-46,2,2,-92,3,1,-69,2,2,-76,2,2,-40,2,2,61,3,1,59,1,3,68,1,-3,54,-3,0,-58,2,0,-61,-2,1,-66,-2,0,64,-2,1,-86,1,-2,69,-1,2,-80,-1,2,-67,-2,-1,57,2,1,-51,2,1,-63,-1,-2],
    [0,33108,6,1,-3384,1393,-3,628,1386,3,-483,973,5,-81,-610,-7,-461,280,4,-83,468,-4,-36,-358,-9,231,58,-1,198,16,7,-160,-102,11,117,-132,2,-169,-26,-11,72,128,-6,-81,71,13,-11,91,9,66,-64,-10,84,-29,-5,69,52,-14,-41,54,23,32,55,-19,47,41,12,21,-51,10,26,48,-2,48,-26,-15,35,-30,20,27,-35,24,27,34,19,28,-32,18,35,-9,-8,-11,35,6,-23,26,17,10,33,-17,-22,-24,-13,3,-31,25,-30,-3,15,24,15,-16,1,27,-12,25,10,-18,26,6,8,24,11,21,17,19,30,-3,24,22,-20,12,16,-2,-23,26,10,-18,29,-9,-19,-20,17,11,32,7,20,-23,20,4,36,-19,5,28,12,12,14,-12,-11,-36,16,5,-21,1,-16,-26,15,6,-22,-16,0,-35,12,-8,-28,13,-5,35,-12,5,-24,-12,-1,41,11,-1,-48,-4,-10,-33,-8,6,-45,7,7,38,10,1,33,4,9,-29,0,9,31,6,7,-34,7,5,40,-8,-2,-65,3,7,48,3,-6,42,-7,-1,-27,4,6,-25,-2,-7,37,-3,-6,52,7,-1,34,0,-7,-60,-2,6,-31,4,-4,49,-2,-5,-39,5,1,-77,5,-3,27,0,5,-32,-5,2,44,-3,-4,-51,3,-5,53,4,3,45,-3,4,-43,3,-4,60,2,4,-72,4,0,50,0,4,61,4,-1,-69,4,-1,-42,4,2,-63,-4,-1,-54,4,-1,-37,-4,0,-46,3,-2,-44,4,-1,-61,-2,-3,-53,-2,3,43,0,4,-64,2,3,-50,-1,3,-75,0,4,65,0,3,39,-2,2,-78,2,-3,58,2,-3,-56,-2,3,-81,-1,-3,-82,0,3,70,2,1,-38,-3,1,-55,-2,-2,-57,3,0,-86,3,-1,55,-2,-1,51,-1,-3,-67,-2,2,-90,-2,-2,-73,-1,2,-74,1,2,-79,2,0,66,-2,1,-41,-2,-1],
    [0,45120,-920,1,799,3231,-2,-910,1433,2,560,744,3,-415,-283,4,458,183,-5,460,5,-1,-98,316,-7,234,110,-3,213,-84,-4,121,-185,5,168,60,-8,111,87,8,92,-99,7,115,-30,-6,-85,-80,10,-4,-97,9,-17,92,16,73,24,-9,-24,-72,-14,53,-10,13,12,41,19,14,-39,-13,-20,-32,11,30,-21,18,-12,34,-12,19,-30,-10,-10,31,14,29,14,17,28,-14,-15,-22,-22,-16,28,6,25,15,20,15,4,24,21,-15,17,-11,7,20,24,-7,19,20,13,10,12,-7,15,-25,1,16,-19,-16,0,-18,-14,-6,27,-1,14,6,-14,-4,28,8,-10,-20,-4,-12,22,-9,8,-24,-10,6,36,2,11,23,11,2,-36,2,10,-45,3,9,-34,4,8,-27,-1,9,-23,8,3,30,-8,1,-17,8,-4,-26,-5,-7,-35,-4,-7,-28,-8,-1,-33,4,6,33,-5,5,29,0,7,26,4,-5,-48,-3,6,45,-2,6,-30,3,5,-54,4,4,-57,1,5,-31,5,-2,32,5,1,-22,-5,0,-32,0,4,31,0,-4,40,4,-2,-37,-1,-4,-41,-2,3,35,2,-3,48,0,3,-46,1,-3,-40,0,-3,-60,-3,2,-42,3,0,34,-1,3,-39,-2,2,-53,3,0,-44,-2,-2,-56,1,2,-62,2,-2,50,-2,0,-69,-2,2,-66,2,2,-21,-2,1,-77,2,1,-70,2,-1,-61,2,-1,37,2,1,-55,2,-1,-64,2,0,39,1,2,41,-1,2,-29,-1,-2,86,2,1,-73,2,1,46,-1,1,-51,-2,0,-47,-1,2,38,1,2,74,1,1,85,2,0,-50,0,2,-72,-2,1,89,1,-1,95,0,2,94,1,1,80,0,-2,69,0,-2,52,-1,0,49,1,-1,-67,-1,-1,43,-1,-1,70,1,1,-38,1,-1,79,1,1,83,0,1,-79,1,0,-86,1,0,47,1,1,-74,0,-1],
  ];

  const FILL = 0.96; // fraction of the container width the word spans
  const MAX_HEIGHT = 0.45; // fraction of the container height the letters may use

  const SAMPLES = 512; // points per contour when drawing
  const N_TRACE = 9; // terms used by the epicycles
  const N_MAX = 128; // terms at the end of the convergence phase
  const MAX_DPR = 1.5; // faint background: full retina resolution is wasted memory

  // Timeline (seconds)
  const T_TRACE = 4.2;
  const T_HOLD = 0.6;
  const T_CONVERGE = 3.6;

  // How the animation ends — data-end on the element, or ?fx-end=… in the URL
  // to compare without editing the HTML:
  //   "outline"   the converged curve stays a line; the stroke pulses once
  //   "fill"      the shape fills in and stays filled
  //   "fill-fade" fills in, holds, then fades back to the outline
  const END_DURATIONS = { outline: 0.9, fill: 0.9, "fill-fade": 2.4 };
  const END = (() => {
    let v = null;
    try {
      v = new URLSearchParams(window.location.search).get("fx-end");
    } catch (error) {
      // Ignore malformed URLs.
    }
    v = v || container.dataset.end;
    return Object.hasOwn(END_DURATIONS, v) ? v : "outline";
  })();
  container.dataset.end = END; // CSS tunes the layer's opacity per style
  const T_END = END_DURATIONS[END];
  const T_TOTAL = T_TRACE + T_HOLD + T_CONVERGE + T_END;

  // ---------- Fourier series ----------

  const COS = new Float64Array(SAMPLES);
  const SIN = new Float64Array(SAMPLES);
  for (let m = 0; m < SAMPLES; m++) {
    COS[m] = Math.cos((2 * Math.PI * m) / SAMPLES);
    SIN[m] = Math.sin((2 * Math.PI * m) / SAMPLES);
  }

  // z(t) = Σ c_f e^{2πi f t}, terms in chaining / detail order.
  const unpack = (flat) => {
    const terms = [];
    for (let i = 0; i < flat.length; i += 3) {
      const freq = flat[i];
      const re = flat[i + 1] / COEF_SCALE;
      const im = flat[i + 2] / COEF_SCALE;
      terms.push({ freq, step: ((freq % SAMPLES) + SAMPLES) % SAMPLES, re, im, amp: Math.hypot(re, im) });
    }
    return terms;
  };

  // Partial sum with a fractional number of terms n (the last term is
  // weighted by n - floor(n) so the curve sharpens continuously).
  const partialSum = (terms, n, out) => {
    const M = SAMPLES;
    const whole = Math.floor(n);
    const frac = n - whole;
    out.fill(0);
    const count = Math.min(terms.length, whole + 1);
    for (let i = 0; i < count; i++) {
      const t = terms[i];
      const w = i < whole ? 1 : frac;
      if (w === 0) continue;
      const re = t.re * w, im = t.im * w;
      let m = 0;
      for (let j = 0; j < M; j++) {
        out[2 * j] += re * COS[m] - im * SIN[m];
        out[2 * j + 1] += re * SIN[m] + im * COS[m];
        m += t.step;
        if (m >= M) m -= M;
      }
    }
    return out;
  };

  let shapes = null; // computed lazily on first play

  const buildShapes = () =>
    TERMS.map((flat) => {
      const terms = unpack(flat);
      return { terms, rough: partialSum(terms, N_TRACE, new Float64Array(2 * SAMPLES)) };
    });

  // ---------- rendering ----------

  const canvas = document.createElement("canvas");
  canvas.style.cssText = "display:block;width:100%;height:100%;";
  container.appendChild(canvas);
  const ctx = canvas.getContext("2d");
  const scratch = new Float64Array(2 * SAMPLES);

  const clamp01 = (x) => Math.max(0, Math.min(1, x));
  const smooth = (x) => x * x * (3 - 2 * x);

  // Fill opacity and stroke-width multiplier during the ending.
  const endState = (time) => {
    const e = clamp01((time - T_TRACE - T_HOLD - T_CONVERGE) / T_END);
    if (END === "fill") return { fill: smooth(e), pulse: 1 };
    if (END === "fill-fade") {
      return { fill: smooth(clamp01(e / 0.35)) * (1 - smooth(clamp01((e - 0.6) / 0.4))), pulse: 1 };
    }
    return { fill: 0, pulse: 1 + 0.9 * Math.sin(Math.PI * e) };
  };

  const readColors = () => {
    const s = getComputedStyle(document.documentElement);
    const v = (name, fallback) => s.getPropertyValue(name).trim() || fallback;
    return {
      ink: v("--color-text", "#edf3fa"),
      accent: v("--color-accent", "#77b3f0"),
      subtle: v("--color-text-subtle", "#acc2d8"),
    };
  };

  let colors = readColors();
  let view = { scale: 1, ox: 0, oy: 0, dpr: 1 };
  let startTime = null;
  let rafId = 0;

  const px = (n) => n / view.scale; // CSS px -> word units
  // Outline width in CSS px: thin, growing slightly with the word's size.
  const strokePx = () => Math.max(0.75, Math.min(1.1, view.scale / 600));

  const resize = () => {
    const rect = container.getBoundingClientRect();
    const dpr = Math.min(window.devicePixelRatio || 1, MAX_DPR);
    canvas.width = Math.max(1, Math.round(rect.width * dpr));
    canvas.height = Math.max(1, Math.round(rect.height * dpr));
    view = {
      scale: Math.min(rect.width * FILL, (rect.height * MAX_HEIGHT) / WORD_HEIGHT),
      ox: rect.width / 2,
      oy: rect.height / 2,
      dpr,
    };
  };

  const tracePath = (pts, upto = SAMPLES, close = true) => {
    ctx.moveTo(pts[0], pts[1]);
    for (let j = 1; j < upto; j++) ctx.lineTo(pts[2 * j], pts[2 * j + 1]);
    if (close) ctx.closePath();
  };

  const drawEpicycles = (shape, t, alpha) => {
    const { terms } = shape;
    let x = terms[0].re, y = terms[0].im;
    ctx.lineWidth = px(0.75);
    for (let i = 1; i <= N_TRACE; i++) {
      const c = terms[i];
      const a = 2 * Math.PI * c.freq * t;
      const nx = x + c.re * Math.cos(a) - c.im * Math.sin(a);
      const ny = y + c.re * Math.sin(a) + c.im * Math.cos(a);
      ctx.globalAlpha = 0.35 * alpha;
      ctx.strokeStyle = colors.subtle;
      ctx.beginPath();
      ctx.arc(x, y, c.amp, 0, 2 * Math.PI);
      ctx.stroke();
      ctx.globalAlpha = 0.6 * alpha;
      ctx.strokeStyle = colors.ink;
      ctx.beginPath();
      ctx.moveTo(x, y);
      ctx.lineTo(nx, ny);
      ctx.stroke();
      x = nx;
      y = ny;
    }
    ctx.globalAlpha = 1;
    return [x, y];
  };

  const draw = (time) => {
    const { scale, ox, oy, dpr } = view;
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    if (!shapes) return;
    ctx.setTransform(scale * dpr, 0, 0, scale * dpr, ox * dpr, oy * dpr);
    ctx.lineJoin = "round";
    ctx.lineCap = "round";
    const stroke = px(strokePx());

    if (time < T_TRACE + T_HOLD) {
      // Phase 1: epicycles trace the N_TRACE-term curve.
      const t = clamp01(time / T_TRACE);
      const circleAlpha =
        smooth(clamp01(time / 0.4)) * (1 - smooth(clamp01((time - T_TRACE) / T_HOLD)));
      const upto = Math.floor(t * SAMPLES);
      for (const shape of shapes) {
        const [tx, ty] = circleAlpha > 0 ? drawEpicycles(shape, t, circleAlpha) : [0, 0];
        ctx.strokeStyle = colors.ink;
        ctx.lineWidth = stroke;
        ctx.beginPath();
        tracePath(shape.rough, upto + 1, t >= 1);
        if (t < 1) ctx.lineTo(tx, ty);
        ctx.stroke();
        if (t < 1) {
          ctx.fillStyle = colors.accent;
          ctx.beginPath();
          ctx.arc(tx, ty, px(2), 0, 2 * Math.PI);
          ctx.fill();
        }
      }
      return;
    }

    // Phase 2: add terms until the partial sums converge on the glyphs.
    const u = clamp01((time - T_TRACE - T_HOLD) / T_CONVERGE);
    const n = N_TRACE * Math.pow(N_MAX / N_TRACE, smooth(u));
    const { fill: fillAlpha, pulse } = endState(time);
    ctx.beginPath();
    for (const shape of shapes) tracePath(partialSum(shape.terms, n, scratch));
    if (fillAlpha > 0) {
      ctx.globalAlpha = fillAlpha;
      ctx.fillStyle = colors.ink;
      ctx.fill("evenodd");
      ctx.globalAlpha = 1;
    }
    ctx.strokeStyle = colors.ink;
    ctx.lineWidth = stroke * pulse;
    ctx.stroke();
  };

  // Once finished, replace the canvas with an inline SVG of the final frame:
  // the canvas backing store (MBs on large screens) is freed, the vector stays
  // sharp at any size, and theme/resize are handled by CSS with no script.
  let done = false;
  const finish = () => {
    const r = (v) => Math.round(v * 1e4) / 1e4;
    let d = "";
    for (const shape of shapes) {
      const p = partialSum(shape.terms, N_MAX, scratch);
      d += `M${r(p[0])} ${r(p[1])}L`;
      for (let j = 1; j < SAMPLES; j++) d += `${r(p[2 * j])} ${r(p[2 * j + 1])} `;
      d += "Z";
    }
    // Same fit rule as resize(): meet = min(width·FILL, height·MAX_HEIGHT/WORD_HEIGHT).
    const vw = 1 / FILL, vh = WORD_HEIGHT / MAX_HEIGHT;
    const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg.setAttribute("viewBox", `${-vw / 2} ${-vh / 2} ${vw} ${vh}`);
    svg.setAttribute("preserveAspectRatio", "xMidYMid meet");
    svg.style.cssText = "display:block;width:100%;height:100%;overflow:visible;";
    const path = document.createElementNS("http://www.w3.org/2000/svg", "path");
    path.setAttribute("d", d);
    path.setAttribute("fill-rule", "evenodd");
    path.setAttribute("vector-effect", "non-scaling-stroke");
    path.setAttribute("stroke-linejoin", "round");
    path.setAttribute("stroke-width", String(strokePx()));
    path.style.cssText = `fill:${END === "fill" ? "var(--color-text,#edf3fa)" : "none"};stroke:var(--color-text,#edf3fa);`;
    svg.appendChild(path);
    container.appendChild(svg);
    canvas.width = canvas.height = 0; // release the backing store right away
    canvas.remove();
    done = true;
  };

  const tick = (now) => {
    const time = (now - startTime) / 1000;
    draw(time);
    if (time < T_TOTAL) rafId = requestAnimationFrame(tick);
    else finish();
  };

  const play = () => {
    shapes ??= buildShapes();
    cancelAnimationFrame(rafId);
    resize();
    // Reduced motion: show the finished word without animating.
    const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    startTime = performance.now() - (reduce ? T_TOTAL * 1000 : 0);
    rafId = requestAnimationFrame(tick);
  };

  // Repaint once when idle (after the animation, or before it has started).
  const redrawIdle = () => {
    if (startTime === null || done) return;
    const time = (performance.now() - startTime) / 1000;
    if (time >= T_TOTAL) draw(T_TOTAL);
  };

  new ResizeObserver(() => {
    if (done) return; // the SVG scales itself
    resize();
    redrawIdle();
  }).observe(container);

  const onTheme = () => {
    colors = readColors();
    redrawIdle();
  };
  new MutationObserver(onTheme).observe(document.documentElement, {
    attributes: true,
    attributeFilter: ["data-theme"],
  });
  window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change", onTheme);

  // Start the first time the hero is on screen.
  const io = new IntersectionObserver((entries) => {
    if (entries.some((e) => e.isIntersecting)) {
      io.disconnect();
      play();
    }
  });
  io.observe(container);
})();
